### ISSUE TITLE
Add "subscribe" link to qa.d.o pages directly

### ISSUE THREAD

**Issue by timplunkett** [Lullabot/drupal_qa_notifier#3]
When running branch tests, there is no patch to have a button next to.
Also, people often past qa.d.o links directly into IRC.

So a button on a page like https://qa.drupal.org/pifr/test/808473 would be very useful to me.

**Comment by timplunkett** [comment]
Since comments now have render caching on, when they get picked up by a bot you can't always see the link on the comment. This makes having a button on the qa page even more important.

**Comment by justafish** [comment]
New version with this feature should be in the chrome store shortly!
